### PR TITLE
Added progressCallback to function

### PR DESCRIPTION
**Pull request by thehobbit85**
there is a built-in option in the scrypt module that allows the user to pass a progressCallback function in order to track the progress of of the encryption/decryption.
It's extremely useful when trying to build any type of UI progress bar or something similar.

I also did some linting and fixed the Build badge link....

### CODE REVIEW

**Comment by jprichardson** [comment]
I like this. But why comment out the tests? https://github.com/thehobbit85/bip38/commit/d228d95321c1bd794e083a4b00aa7a79311adca2 Especially in a commit where it doesn't make sense to?

**Comment by thehobbit85** [comment]
Since I'm an idiot who forgot to put them back :)
I wanted to see why the build was failing so I only left the short test so that the build will go faster.
Again, just to check something out and then I just forgot that... So here, I just returned them back to their place :)

**Comment by thehobbit85** [comment]
I also made a small fix to the coverall script but now it seems this repo is not being tracked on coveralls so you also need to check that.

**Comment by dcousens** [comment]
@thehobbit85 for easy merging, if you could split up those non-`progressCallback` commits into other PRs so they can be merged straight away, that'd be awesome.

Also, rebase/squash your mistakes, :+1:

**Pull request closed without merging**
