### PR TITLE
Add async

### PR DESCRIPTION
**Pull request by junderw**
Initial refactor with async added...

README etc. and any nitpicks are welcome.

### CODE REVIEW

**Comment by jprichardson** [comment]
@lukechilds please review.

**Comment by lukechilds** [comment]
This looks good to me.

We should mention in the readme about the async perf performance, or just link to the `scryptsy` readme.

**Comment by Overtorment** [comment]
bump

**Comment by junderw** [comment]
Rebased

**Comment by junderw** [comment]
I stopped the 3.1.0 commit job

**Comment by junderw** [comment]
published as 3.1.0

**Pull request merged**
