### PR TITLE
Some minor fixes and adding progressCallback functionality

### PR DESCRIPTION
**Pull request by thehobbit85**
1. Added progressCallback to module functions
2. Added progressCallback explanation to the Readme
3. Fixed problem with travis badge and added standard badge to readme
4. Added coverage and logs to gitignore
5. Small fix to npm coveralls script

### CODE REVIEW

**Comment by dcousens** [comment]
ACK on everything. LGTM.

**Comment by dcousens** [comment]
Tests are good, just coveralls dying for some reason.  91% coverage.

**Comment by thehobbit85** [comment]
I think the coveralls die since the repo at coverall is still set to cryptocoinjs/bip38 instead of bitcoinjs/bip38.
Need to fix that at coveralls.io

**Comment by jprichardson** [comment]
Thanks, reviewing...

**Comment by jprichardson** [comment]
> Need to fix that at coveralls.io

Tried re-syncing coveralls... but bitcoinjs repo doesn't show up. @dcousens you may need to add it on your end because you're an owner?

**Comment by dcousens** [comment]
@jprichardson I think I enabled it.  Time will tell.

**Pull request merged**
