### PR TITLE
README: add scrypt params

### PR DESCRIPTION
**Pull request by dcousens**
@jprichardson do we want anything more than that?

### CODE REVIEW

**Comment by jprichardson** [comment]
> @jprichardson do we want anything more than that?

It's good enough for now.

**Comment by dcousens** [comment]
Release?

**Comment by jprichardson** [comment]
> Release?

Please update the changelog 😛

**Comment by jprichardson** [comment]
Ah, nevermind, I thought you bumped the package. I got it... I like to keep them in the same commit. Publishing shortly.

**Comment by jprichardson** [comment]
Published.

**Pull request merged**
